version: "3.5"
services:
  app:
    build:
      dockerfile: "./docker/Dockerfile"
      context: .
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - "./.env:/var/www/app/.env"
      - "./cron:/etc/crontabs/root"
